// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config';
import { defineConfig, env } from 'prisma/config';
import dotenv from 'dotenv';
import process from 'process';

dotenv.config({
  path: process.env.NODE_ENV === 'development' ? '.env.development' : '.env',
});

export default defineConfig({
  schema: 'src/common/schemas',
  migrations: {
    path: 'src/common/migrations',
    seed: 'ts-node src/common/db/seed.ts',
  },
  datasource: {
    url: env('DATABASE_URL'),
  },
});
